### ISSUE TITLE
USER STORY: Voting system from the Back-end

### ISSUE THREAD

**Issue by plexoio** [plexoio/my-first-agile-project#5]
## Header
| Metadata   |  Description                |
|------------|--------------------------|
| Theme      | Voting System |
| Epic #2     | Voting system from the Back-end |
| User Story #1 | Create, Publish & Store vote event |

## Definition
| Role               | Capability         | Received Benefit        |
| ------------------ | ------------------ | ----------------------- |
| **As a**         | **I can**   | **so that**  |

## Construction
As an administrator, I want to be able to create vote events. This will allow me to store and publish them on the home page.

## Acceptance Criteria

- Criteria 1: Create a section in the admin panel 'Create Event', where a form will open to create an event.
- Criteria 2: Connect the form in such a way that once created it will store the information.
- Criteria 3: Ability to store first a draft and once decided to click on Publish to make it visible on the home page.
  
## Tasks
- [ ] Task 1: Create proper entry and layout for the creation form using HTML, CSS, and Javascript for validation.
- [ ] Task 2: Connect the form to the database and 2 buttons one for saving the draft and one for publishing.
- [ ] Task 3: Make sure the publish button will publish on the home page and store it in the proper table in the database (RDMS)

## Note
User Story Agreement: card, conversation, confirmation (this).
- Articulate this criterion collaboratively:
  -  User
  - Product Owner
  - Agile Team
