### ISSUE TITLE
USER STORY: Voting system from the Back-end

### ISSUE THREAD

**Issue by plexoio** [plexoio/my-first-agile-project#6]
## Header
| Metadata   |  Description                |
|------------|--------------------------|
| Theme      | Voting system |
| Epic #2     | Voting system from the Back-end |
| User Story #2 | 'Text' |

## Definition
| Role               | Capability         | Received Benefit        |
| ------------------ | ------------------ | ----------------------- |
| **As a**         | **I can**   | **so that**  |

## Construction
As an administrator, I want to be able to properly manage the voting event by storing the users' responses from the home page.

## Acceptance Criteria

- Criteria 1: Make sure the system collects and processes correctly the user's inputs from the homepage.
- Criteria 2: Make sure that users receive proper validation & feedback after voting, on the home page.
- Criteria 3: After submission, important data should be visible from the admin panel: votes, feedback, and comments, adding an update to the user's personal events, as 'voted' for a particular event. Only one vote should be allowed per event if required so.
  
## Task
- [ ] Task 1: Connect front-end & back-end for user's goals, updating the database properly.
- [ ] Task 2: Add and test the form validation as well as provide alerts of completion.
- [ ] Task 3: Get the updated database from the admin panel without accessing it directly, updating the user's profile and general stats respectively (db tables), note single vote event no avoid duplicates.

## Note
User Story Agreement: card, conversation, confirmation (this).
- Articulate this criterion collaboratively:
  - User
  - Product Owner
  - Agile Team
